name: esmabatu
description: Esma Batuhan Wedding


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  get_storage: ^2.1.1
  get: ^4.6.5
  url_launcher: ^6.0.14
  image_picker: ^1.0.4
  camera: ^0.10.5+4
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true


  assets:
    - assets/

